name: Deploy to Production
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ./github_action_key
        sudo chmod 600 ./github_action_key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    - name: Install PM2
      run: npm install -g pm2
    - name: Deploy
      run: pm2 deploy ecosystem.config.js production
    - name: Create .env
      shell: bash
      run: |
        touch .env
        echo APPWRITE_ENDPOINT=${{secrets.APPWRITE_ENDPOINT}} >> .env
        echo APPWRITE_API_KEY=${{secrets.APPWRITE_API_KEY}} >> .env
        echo PILCC_PROJECT_ID=${{secrets.PILCC_PROJECT_ID}} >> .env
        echo CLIP_DATABASE_ID=${{secrets.CLIP_DATABASE_ID}} >> .env
        echo CLIP_COLLECTION_ID=${{secrets.CLIP_COLLECTION_ID}} >> .env
        scp -o StrictHostKeyChecking=no .env -P 33621 ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/var/www/Pilcc/source
